/** Bitmap do ponteiro padrão do Windows (32×32, hotspot 0,0). */
export const WINDOWS_CURSOR_SIZE = 32;

export const WINDOWS_ARROW_CURSOR_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADXSURBVFhH7dLBC4IwFMdxZ/Og5fD//zfq2Mlb/4B0lS7SSUio6DD5jSZjmAX29i77QjCE8T4+S4QodVGUOuEKgI1UfAgAEBvCAtgQLoAF4QOCI+YAKBjiEwAFQSwBHs8XPWIJgPr+Rov4BkBdd6VD/AJAbXsxCP/+6nzAMNynMwb6P//+6lwAhotE6f3hOAHynGComwXY4fjOaarMM6wdZ//OXwPAHY5nUla6rk8GgTPpFrBmdzhyt9A0Z/otzIU3x3DzX+AA7N5byLJKbyk/QSwWi8Vi3I0kaHdgrLh7TwAAAABJRU5ErkJggg==';
